// Include other dependencies
#define _USE_MATH_DEFINES
#include <math.h>
#include <iostream>
#include <cstdlib> 
#include <fstream>
#include <opencv2/opencv.hpp>
#include <opencv2/core/utils/logger.hpp>
#include <opencv2/core/parallel/parallel_backend.hpp>
#include <opencv2/core/types.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/features2d.hpp>
#include <Eigen/Core>
#include <vector>
#include <chrono>
#include <thread>
#include <stdexcept>
#include <string> 
#include <random>
#include <filesystem>
#include <filesystem>
#include <limits>
#include <stdio.h>